import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import "./global.css"
import BootstrapClient from "./components/BoostrapClient";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar/>
        {children}
        <BootstrapClient/>

      </body>
    </html>
  );
}
